[phases.setup]
nixPkgs = ["python38", "postgresql", "pipenv", "gcc"]
aptPkgs = ["libmysql-client", "libssl-dev", "libgl1"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && ./opt/venv/bin/activate && pip install -r requirements.txt"

[phases.start]
cmd = "gunicorn run:app"