SUCCESS = {
    "SUCCESS_WELCOME": "Welcome to the Callisto Protocol",
    # pylint: disable-next=line-too-long
    "SUCCESS_USER_REGISTER": "Successfully registered a new user. Please check your email to verify your account.",
    "SUCCESS_USER_VERIFICATION": "Successfully verfied user.",
    "SUCCESS_LOGIN": "Logged in successfully.",
    "SUCCESS_SEND_OTP": "Successfully send OTP code.",
    "SUCCESS_OTP_VALIDATION": "OTP code validation was successful.",
    "SUCCESS_USER_DETAIL": "Successfully displayed user details.",
    "SUCCESS_UPDATE_USER": "Successfully updated user details.",
    "SUCCESS_UPDATE_PASSWORD": "Successfully updated user password.",
    "SUCCESS_UPDATE_PICTURE": "Successfully update user picture.",
    "SUCCESS_LOGOUT": "Logged out successfully.",
    "SUCCESS_GET_ALL_TPS": "Successfully get all tps.",
    "SUCCESS_ADD_TPS": "TPS successfully created.",
}

ERROR = {
    "ERROR_USER_REGISTER": "Failed to register new user.",
    "ERROR_PASSWORD_RETYPE": "Password ins't same !.",
    "ERROR_EMAIL_ALREADY_EXISTS": "This email has been used !.",
    "ERROR_LOGIN_NO_DATA": "Login failed, please enter email and password !.",
    "ERROR_LOGIN_INCORRECT_DATA": "Login failed, wrong email or password !.",
    "ERROR_INTERNAL_SERVER": "Oops, something went wrong. Please try again later.",
    "ERROR_OTP_CODE_INVALID": "Your OTP code does not match or has expired !.",
    "ERROR_EMAIL_INCORRECT": "Email not found !.",
    "ERROR_BAD_REQUEST": "Data incorrect or invalid !.",
    "ERROR_KEY_ERROR": "Some required arguments are missing !.",
    "ERROR_EMPTY_PASSWORD": "Password cannot be empty !.",
    "ERROR_DB_SERVER": "Can't connect to Database Server !.",
    "ERROR_UNVERIFIED_USER": "The user hasn't verified the email. Please verify email first !.",
    "ERROR_UPDATE_PASSWORD": "Failed to update user password !.",
    "ERROR_UPDATE_PICTURE": "Failed to update user picture !.",
    "ERROR_INVALID_FILE_TYPE": "Unsupported file format.",
    "ERROR_ACCESS_DENIED": "You don't have permission to access !.",
}
